# @package _global_
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields:
    - emg_left
    - emg_right

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120

logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16

transforms:
  train:
    - ${to_tensor}
    - ${temporal_jitter}
    - ${logspec}
  val:
    - ${to_tensor}
    - ${logspec}
  test: ${transforms.val}